###############################################################
#  Generated by:      Cadence Innovus 23.33-s082_1
#  OS:                Linux x86_64(Host ID vlsi-ria84)
#  Generated on:      Tue Jun 16 16:53:06 2026
#  Design:            top
#  Command:           saveDesign postCTS_final.enc
###############################################################
current_design top
create_clock [get_pins {I9/I1/PAD}]  -name I9/I1/PAD -period 10.000000 -waveform {0.000000 5.000000}
#END OF CLOCK SECTION#
