###############################################################
#  Generated by:      Cadence Innovus 23.33-s082_1
#  OS:                Linux x86_64(Host ID vlsi-ria87)
#  Generated on:      Fri Jun 26 02:05:08 2026
#  Design:            top
#  Command:           saveDesign top -tcon
###############################################################
current_design top
create_clock [get_pins {I9/I1/PAD}]  -name I9/I1/PAD -period 12.000000 -waveform {0.000000 6.000000}
#END OF CLOCK SECTION#
